/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings/diagnostics'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsProcessingRouteImport } from './routes/settings/processing'
import { Route as SettingsRecognitionRouteImport } from './routes/settings/recognition'
import { Route as SettingsVoiceInputRouteImport } from './routes/settings/voice-input'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProcessingRoute = SettingsProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRecognitionRoute = SettingsRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVoiceInputRoute = SettingsVoiceInputRouteImport.update({
  id: '/voice-input',
  path: '/voice-input',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/processing': typeof SettingsProcessingRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/voice-input': typeof SettingsVoiceInputRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/onboarding': typeof OnboardingRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/processing': typeof SettingsProcessingRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/voice-input': typeof SettingsVoiceInputRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/processing': typeof SettingsProcessingRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/voice-input': typeof SettingsVoiceInputRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/onboarding'
    | '/settings'
    | '/settings/about'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/processing'
    | '/settings/recognition'
    | '/settings/voice-input'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/onboarding'
    | '/settings/about'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/processing'
    | '/settings/recognition'
    | '/settings/voice-input'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/onboarding'
    | '/settings'
    | '/settings/about'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/processing'
    | '/settings/recognition'
    | '/settings/voice-input'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/processing': {
      id: '/settings/processing'
      path: '/processing'
      fullPath: '/settings/processing'
      preLoaderRoute: typeof SettingsProcessingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/recognition': {
      id: '/settings/recognition'
      path: '/recognition'
      fullPath: '/settings/recognition'
      preLoaderRoute: typeof SettingsRecognitionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/voice-input': {
      id: '/settings/voice-input'
      path: '/voice-input'
      fullPath: '/settings/voice-input'
      preLoaderRoute: typeof SettingsVoiceInputRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsProcessingRoute: typeof SettingsProcessingRoute
  SettingsRecognitionRoute: typeof SettingsRecognitionRoute
  SettingsVoiceInputRoute: typeof SettingsVoiceInputRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsProcessingRoute: SettingsProcessingRoute,
  SettingsRecognitionRoute: SettingsRecognitionRoute,
  SettingsVoiceInputRoute: SettingsVoiceInputRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
